baseurl: /eugene
permalink: pretty
markdown: kramdown
paginate: 5
repo: eugene
github_org: maptime
maptime:
  chapter: MaptimeEUG
  twitter: TwitterHandle
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
